sequenceDiagram

title ON POSITION INCREASED

participant BIN as Binance
participant FIN as Finandy
participant STG as Strategy
participant OLS as Order Listener (GLOBAL)

BIN ->>+ OLS: Send 'order'
OLS ->>  BIN: Ask 'position[ order.pair ]'
BIN ->>  OLS: Send 'position[ order.pair ]'
OLS ->>  OLS: Set 'type'
OLS ->>- STG: Send {'type', 'order', 'position[ order.pair ]'}
alt 
    Note over STG: type == "INCREASE_ORDER_FILLED"
    alt
        Note over STG: this.dir == order.dir <br> and <br> this.pair == order.pair
        STG ->> BIN: Post tp_order[ this.pair ][ this.dir ]
        STG ->> FIN: Post reverse_trailing_order[ this.pair ][ ! this.dir ]
        STG ->> STG: Update 'breakeven'
    end
    alt
        Note over STG: this.dir == order.dir <br> and <br> this.pair != order.pair
        STG ->> BIN: Ask 'position[ this.pair ]'
        BIN ->> STG: Send 'position[ this.pair ]'
        STG ->> STG: Update 'breakeven'
        alt
            Note over STG: position[ this.pair ][ this.dir ].qty == 0
            STG ->> BIN: Ask 'pending_orders[ this.pair ]'
            BIN ->> STG: Send 'pending_orders[ this.pair ]'
            alt
                Note over STG: len( pending_orders[ this.pair ][ this.dir ] ) > 0
                STG ->> BIN: Cancel pending_orders[ this.pair ][ this.dir ]

            end
            STG ->> FIN: Post reverse_trailing_order[ this.pair ][ this.dir ]
        end
    end 
end